### ISSUE TITLE
add "places of composition" map to "geography" tab in details panel

### ISSUE THREAD

**Issue by stefanprobst** [acdh-oeaw/mmp-frontend#104]
in the sidepanel on the network-graph page - e.g. https://acdh-oeaw.github.io/mmp-frontend/#/explore/graph/detail/640?Use%20Case=3 - the "geography" tab should display a map with "places of composition" related to a "keyword"

**Comment by stefanprobst** [comment]
tab title suggestion: "places"

**Comment by kaggl** [comment]
we did it
