### ISSUE TITLE
perf: Add pagination to components where it might be needed

### ISSUE THREAD

**Issue by kaggl** [acdh-oeaw/mmp-frontend#153]
Some api endpoints use pagination, which i ignore most of the time.
To ensure proper scaling, I want to implement proper pagination sometime in the future.

**Comment by stefanprobst** [comment]
- requests are paginated currently on the "list passages" and "list all entities" data tables only
- the "case study" screen [uses a `limit` of 200](https://github.com/acdh-oeaw/mmp-frontend/blob/c81d86e15d780851bde8a3bd1866e6305262e84d/src/components/CaseStudy.vue#L190) when fetching associated passages, which is not great performance-wise unfortunately:
  ```bash
  time curl "https://mmp.acdh-dev.oeaw.ac.at/api/stelle/?use_case=5&limit=200"
  real    0m7,559s
  ```

**Comment by stefanprobst** [comment]
also: https://github.com/acdh-oeaw/mmp-frontend/blob/6bf797521287f904c4b9befc5060a3cea2490374/src/components/KeywordDetail.vue#L38

**Comment by stefanprobst** [comment]
maybe we need an additional endpoint to query passages by text by author

**Comment by stefanprobst** [comment]
won't fix
