### ISSUE TITLE
show point layer(s) for places

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/mmp-frontend#33]
as of [v1.17](https://github.com/acdh-oeaw/mmp/releases/tag/v1.17) there is another endpoint for Places returning data as GeoJSON e.g. https://mmp.acdh-dev.oeaw.ac.at/api/ort-geojson/?format=json
use this data to add another (selectable) layers to the mapview
* Places related to Authors
* Places related to Texts
* Places related to Passages

**Comment by kaggl** [comment]
this should be fully covered by c04385e97d8a7280b80117e12df13cf0699c28ed
