### ISSUE TITLE
implement story-maps

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/mmp-frontend#41]
Some use case have provided some "story-maps" which need to be implemented into the frontend; I'm not sure if those story maps provided via the API can be converted completly automatically by the frontend into a nice looking, interactive site or if you have to manually create/hard code those pages.

**Comment by csae8092** [comment]
see e.g. https://mmp.acdh-dev.oeaw.ac.at/api/usecase/4/?format=json which nicely includes some images and some structual html markup as `h1` as well as iframes (which in the frontend version should obviously be replaced by their matching components)

**Comment by stefanprobst** [comment]
x-ref #134
