### ISSUE TITLE
dates in text detail view

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/mmp-frontend#44]
> Übernahme der Entstehungsdaten bei Werken, z.B. Widukind von Korvey: im backend ist das Entstehungsdatum eingetragen: https://mmp.acdh-dev.oeaw.ac.at/archiv/text/detail/686 im Frontend wird es nicht angezeigt: MMP - Mapping Medieval Peoples (acdh-oeaw.github.io)  

can be fetched from https://mmp.acdh-dev.oeaw.ac.at/api/text/5/?format=json keys `{"jahrhundert":"4th","start_date":"","end_date":"362","not_before":-100,"not_after":362}`

**Comment by kaggl** [comment]
resolved in 9dd2b1447fefb901ae1845a8253b4c933d0144dc
