### ISSUE TITLE
custom icons

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/mmp-frontend#49]
create/design and implement custom icons for Ort

"art": "https://mmp.acdh-dev.oeaw.ac.at/api/skosconcepts/4/",
"kategorie": "https://mmp.acdh-dev.oeaw.ac.at/api/skosconcepts/5/"

@marcs19 provides the icons, @robin oversees implementation
@csae8092 investigates providing art/kategorie not as URLs but as Objects

**Comment by marcs19** [comment]
Would't it be better to ask the researchers which icons they want to add for which "kategorie"?
The implementation is working so far.
