### ISSUE TITLE
investigate fuzzy polygon boundaries

### ISSUE THREAD

**Issue by csae8092** [acdh-oeaw/mmp-frontend#50]
1) solution make border fuzzy
2) no closed line; maybe dotted line
3) gradient, in the middle of the poly darker, towards the end lighter, higher opacity

or in short, something like https://www.scrapethepast.com/leafletfuzzy/

**Comment by marcs19** [comment]
1. Polygons are now fuzzy!
2. No line at all for the moment, we can discuss this maybe in our next MMP meeting.
3. No gradient for the moment, maybe it is ok the way it now is for the moment (can maybe make it fancier later on)
